### PR TITLE
Fix "Can shift large amounts of data" test

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/3)

### CODE REVIEW

**Comment by dersim-davaod** [comment]
This is fix for https://github.com/thaliproject/Thali_CordovaPlugin/issues/1761 as well

**Comment by asuhodolov** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/3#-:-Kh6aowg9xkgt2PldMnj:bnfp4nl)*

**Comment by yaronyg** [comment]
Please see my concern about timeouts.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 71 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/3#-Kh8IVrrPNSDZZrIDWkL:-Kh8IVrs5slmgM7ed0GA:b-ps9sz2) ([raw file](https://github.com/thaliproject/thali-ios/blob/401610a9be6e3ac94b34dbfffe537406a718cf3b/ThaliCore/SocketConnection/TCPClient.swift#L71)):*
> ```Swift
> 
>   func socket(_ sock: GCDAsyncSocket, didWritePartialDataOfLength partialLength: UInt, tag: Int) {
>     sock.readData(withTimeout: -1, tag: 0)
> ```

It seems scary to leave a read open indefinitely. How do we make sure this can't be used as a way to drain someone's battery? What other timeouts do we have?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/3#-:-Kh8IpkcV6q47SaZ1aFL:b1g615f)*

**Comment by evabishchevich** [comment]
Already implemented in #6

**Pull request closed without merging**
