### PR TITLE
Apply swiftlint rules

### PR DESCRIPTION
**Pull request by asuhodolov**
Issue https://github.com/thaliproject/Thali_CordovaPlugin/issues/1812

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/8)

### CODE REVIEW

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 5 of 26 files at r1, 21 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/8#-:-KiW6Rhn3I9HQdebDBEu:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/8#-:-KiZEqjKBW3bLMSmrJ8g:bnfp4nl)*

**Comment by jareksl** [comment]
Reviewed 5 of 26 files at r1, 21 of 21 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/8)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Reviewed 5 of 26 files at r1, 21 of 21 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/8#-:-KieshK8qHs038zL4uQe:bnfp4nl)*

**Pull request merged**
