### PR TITLE
Improve code readability in ThaliCore

### PR DESCRIPTION
**Pull request by lesn1kk**
Issue [#1949](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1949)

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/11)

### CODE REVIEW

**Comment by enricogior** [comment]
*[ThaliCore/MultipeerConnectivity/BrowserManager.swift, line 217 at r2](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-KroBh7yvS7qiHNK-XWG:-KroBh7yvS7qiHNK-XWH:benahts) ([raw file](https://github.com/thaliproject/thali-ios/blob/65c16e8afeb741c8709c57b6c52ba798a692b7ce/ThaliCore/MultipeerConnectivity/BrowserManager.swift#L217)):*
> ```Swift
>                             guard let strongSelf = self else { return }
> 
>                             strongSelf.activeRelays.modify { activeRelay in
> ```

`activeRelay` shoud be `activeRelays`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11)*

**Comment by enricogior** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-:-KroCuolcPdLRzC-UBiO:bnfp4nl)*

**Comment by enricogior** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-:-Ks57mJIKRXti6Lu4HRS:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 12 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[ThaliCore/Core/Dictionary+KeyForValue.swift, line 19 at r3](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-Ks80fB_KBFryqSFNUk_:-Ks80fB_KBFryqSFNUka:b-mscf27) ([raw file](https://github.com/thaliproject/thali-ios/blob/b0616efefa16db5b868cfb386e9b6bcd3f6b69ee/ThaliCore/Core/Dictionary+KeyForValue.swift#L19)):*
> ```Swift
>                .map { element in
>                   element.0
>                 }
> ```

NB: Personally I don't think that this particular change increases readability of a code because variable names are very general. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-:-Ks82vzQiyQuMvCMYi5t:bg7igkv)*

**Comment by enricogior** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/11#-:-KsA6Kr1cP7Ch2V29iY1:bnfp4nl)*

**Pull request merged**
