### PR TITLE
ThaliCore multiple bugs fixes

### PR DESCRIPTION
**Pull request by enricogior**
There are several issues tracking the bugs fixed in this PR:
https://github.com/thaliproject/Thali_CordovaPlugin/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AiOS%20label%3Aready%20ThaliCore%20in%3Atitle%20

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/10)

### CODE REVIEW

**Comment by yaronyg** [comment]
Please see comments.

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-KpM3C3T9LR-_vf0f-qU:b-r20k0z) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
> ```Swift
>     var proceed = false
>     self.disconnecting.modify {
>       if $0 == false {
> ```

Can't you just use a variable name? It's so much easier to read. This applies to pretty much all uses of the $ syntax.

---

*[ThaliCore/SocketConnection/VirtualSocket.swift, line 37 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM42kQD21-8BpTwM2N:-KpM42kQD21-8BpTwM2O:b-y967g0) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/VirtualSocket.swift#L37)):*
> ```Swift
> 
>   // --- For debugging purpose only ---
>   static var idCounter = 0
> ```

Shouldn't we wrap code like this in an #if? Same for below.

---

*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpM4ZUn289dJErgSQoC:byqhpso) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
> ```Swift
>     mcPeerID = MCPeerID(displayName: String.random(length: 5))
>     mcSessionMock = MCSessionMock(peer: MCPeerID(displayName: String.random(length: 5)))
>     nonTCPSession = Session(session: mcSessionMock,
> ```

I'm surprised not to see more tests that explicit target the pretty complex (out of necessity, I get it) rules you have had to put in to prevent a variety of race conditions. I realize we are testing this by reference at the Node layer but that seems rather hands off given all the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-:-KpM4sDBvQttWTEGu_Ta:bd72ecc)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-KpOLogN7yA6Rk2AkEht:b-46ezi5) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Can't you just use a variable name? It's so much easier to read. This applies to pretty much all uses of the $ syntax.
</blockquote></details>

I agree, that Swift way of  replacing variable names make the code less readable, I didn't take the time to change it but I'm more than glad to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/VirtualSocket.swift, line 37 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM42kQD21-8BpTwM2N:-KpOMzCWj_2VVkKmg8v6:b-4ca1c5) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/VirtualSocket.swift#L37)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Shouldn't we wrap code like this in an #if? Same for below.
</blockquote></details>

In Swift there isn't a predefined way of doing that. It can be done at least in a couple of different ways, using a pre-processor file to define macros or adding a custom compiler flag to each compiler target but having to do that just for one case seems exaggerated.
It's just another example of how Swift is still not fully matured.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/VirtualSocket.swift, line 37 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM42kQD21-8BpTwM2N:-KpOOwl7vvJHJVxnjH7e:b-wbbjdm) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/VirtualSocket.swift#L37)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

In Swift there isn't a predefined way of doing that. It can be done at least in a couple of different ways, using a pre-processor file to define macros or adding a custom compiler flag to each compiler target but having to do that just for one case seems exaggerated.
It's just another example of how Swift is still not fully matured.
</blockquote></details>

One thing I should mention is that the openSockets array and the mutex will be used in retail build when we will fix issue #1933.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpOQUsRqi8sOUllJ5oY:bxp8tyq) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I'm surprised not to see more tests that explicit target the pretty complex (out of necessity, I get it) rules you have had to put in to prevent a variety of race conditions. I realize we are testing this by reference at the Node layer but that seems rather hands off given all the changes.
</blockquote></details>

I understand the benefit of using units test when you don't have to interact with pretty complex network APIs, but in our case we do so I'm not sure these tests can do any real validation given these are unit tests that run on the simulator, use mocks making wrong assumptions on how the mocked components work and don't really do any real world interaction with the network.
When the code has complex rules to avoid race conditions between network components, I believe that should be tested in functional or integration tests on the devices and in general should be written by someone else and not by the same dev that wrote the code otherwise we end up with the same problem we had with the current ThaliCore tests: the tests make the same wrong assumptions made in the code. So at the end we have a long list of unit tests that were passing and still the code was deeply broken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
@yaronyg one more commit added to increase the 'invite to connect' timeout.

**Comment by yaronyg** [comment]
Review status: 22 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpQj_awO0nRqyulGkYJ:blabs2d) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

I understand the benefit of using units test when you don't have to interact with pretty complex network APIs, but in our case we do so I'm not sure these tests can do any real validation given these are unit tests that run on the simulator, use mocks making wrong assumptions on how the mocked components work and don't really do any real world interaction with the network.
When the code has complex rules to avoid race conditions between network components, I believe that should be tested in functional or integration tests on the devices and in general should be written by someone else and not by the same dev that wrote the code otherwise we end up with the same problem we had with the current ThaliCore tests: the tests make the same wrong assumptions made in the code. So at the end we have a long list of unit tests that were passing and still the code was deeply broken.
</blockquote></details>

Alas we have to work with what we have. :( But in regards to running on real devices, we support running Swift tests on native devices (not simulators). See [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/522dfbe7fe4523f63287ea8d5f38e402fa88e334/src/ios/Testing/AppContextTests.swift#L168)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpQldqkdMRjzOPWG_48:bth40rg) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Alas we have to work with what we have. :( But in regards to running on real devices, we support running Swift tests on native devices (not simulators). See [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/522dfbe7fe4523f63287ea8d5f38e402fa88e334/src/ios/Testing/AppContextTests.swift#L168)
</blockquote></details>

I wasn't aware of those tests, when I asked Dersim about ThaliCoreTests he told me they don't run on devices and he didn't mention the file you pointed out. Are there any instructions on how to run them on devices?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpQn6ZqBUMM5QeyUbEp:bwlc3z0) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

I wasn't aware of those tests, when I asked Dersim about ThaliCoreTests he told me they don't run on devices and he didn't mention the file you pointed out. Are there any instructions on how to run them on devices?
</blockquote></details>

Are those the tests executed by https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/UnitTest_app.js#L31 ?
If that is the case they are not what we need to do proper ThaliCore testing, we need to build a Swift app that runs at least on two devices to do some real testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpQnn8C-FcehzbDYGeU:ba77ydu) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Are those the tests executed by https://github.com/thaliproject/Thali_CordovaPlugin/blob/master/test/www/jxcore/UnitTest_app.js#L31 ?
If that is the case they are not what we need to do proper ThaliCore testing, we need to build a Swift app that runs at least on two devices to do some real testing.

</blockquote></details>

The TaliCoreTests that only run on the simulator are these https://github.com/thaliproject/thali-ios/tree/master/ThaliCoreTests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by yaronyg** [comment]
Review status: 22 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpVhPHu_1qANI7QwLib:b-yywxrj) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

The TaliCoreTests that only run on the simulator are these https://github.com/thaliproject/thali-ios/tree/master/ThaliCoreTests
</blockquote></details>

It is the line in UnitTest_App.js but remember that it is calling into arbitrary native code. That code can do absolutely anything it wants to do including using MPCF. The real issue is how to coordinate the tests. That is, how does the test know how many clients there are and how many tests to run. For that you need the coordinator. We have one obviously but you would need to implement the protocol we currently use to talk to it. Not easy of course. But you could cheat and just assume that there is at least one other peer out there and then run the test with that peer. That wouldn't require a coordinator and would be fine for a smoke test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-KpVnTALVxYEa1cPFZcR:b-4be5vs) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

It is the line in UnitTest_App.js but remember that it is calling into arbitrary native code. That code can do absolutely anything it wants to do including using MPCF. The real issue is how to coordinate the tests. That is, how does the test know how many clients there are and how many tests to run. For that you need the coordinator. We have one obviously but you would need to implement the protocol we currently use to talk to it. Not easy of course. But you could cheat and just assume that there is at least one other peer out there and then run the test with that peer. That wouldn't require a coordinator and would be fine for a smoke test.
</blockquote></details>

OK, I see, it's doable, but I don't think we should delay merging this PR to have some more tests, since we are passing 100% of ThaliTest and also ThaliTestApp works just fine. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-KpYy4k-rKTlny-OJxbN:btmtbbc) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

I agree, that Swift way of  replacing variable names make the code less readable, I didn't take the time to change it but I'm more than glad to do it.
</blockquote></details>

There are several ways of writing the Atomic closure's argument name explicitly:

1) the simplest, using a generic 'value' name:

    self.disconnecting.modify { value in
      if value == false {
        value = true
        proceed = true
      }
    }

2) using the same variable name or slightly modified:

    self.disconnecting.modify { disconnecting in
      if disconnecting == false {
        disconnecting = true
        proceed = true
      }
    }

or:

    self.disconnecting.modify { _disconnecting in
      if _disconnecting == false {
        _disconnecting = true
        proceed = true
      }
    }

3) same as 2) plus adding the argument type explicitly:

    self.disconnecting.modify { (disconnecting: inout Bool) in
      if disconnecting == false {
        disconnecting = true
        proceed = true
      }
    }

Do you want the arguments replaced in all closures used in ThaliCore? There are about 70 places (not counting the test code) and the replacement has to be done manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-KpZ30jClWE_RNyUx6Jl:brlgi9h) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

There are several ways of writing the Atomic closure's argument name explicitly:

1) the simplest, using a generic 'value' name:

    self.disconnecting.modify { value in
      if value == false {
        value = true
        proceed = true
      }
    }

2) using the same variable name or slightly modified:

    self.disconnecting.modify { disconnecting in
      if disconnecting == false {
        disconnecting = true
        proceed = true
      }
    }

or:

    self.disconnecting.modify { _disconnecting in
      if _disconnecting == false {
        _disconnecting = true
        proceed = true
      }
    }

3) same as 2) plus adding the argument type explicitly:

    self.disconnecting.modify { (disconnecting: inout Bool) in
      if disconnecting == false {
        disconnecting = true
        proceed = true
      }
    }

Do you want the arguments replaced in all closures used in ThaliCore? There are about 70 places (not counting the test code) and the replacement has to be done manually.

</blockquote></details>

Sorry for the bad formatting of the previous comment.

1. the simplest, using a generic 'value' name:
```
self.disconnecting.modify { value in
  if value == false {
    value = true
    proceed = true
  }
}
```
2. using the same variable name:
```
self.disconnecting.modify { disconnecting in
  if disconnecting == false {
    disconnecting = true
    proceed = true
  }
}
```
3. using the same variable name slightly modified:
```
self.disconnecting.modify { _disconnecting in
  if _disconnecting == false {
    _disconnecting = true
    proceed = true
  }
}
```
4. same as 2. or 3. plus adding the argument type explicitly:
```
self.disconnecting.modify { (disconnecting: inout Bool) in
  if disconnecting == false {
    disconnecting = true
    proceed = true
  }
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by yaronyg** [comment]
Please fix the inline variable issue and then :LGTM:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-Kp_rn6hFr94-7W39SyR:bcwjxqv) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Sorry for the bad formatting of the previous comment.

1. the simplest, using a generic 'value' name:
```
self.disconnecting.modify { value in
  if value == false {
    value = true
    proceed = true
  }
}
```
2. using the same variable name:
```
self.disconnecting.modify { disconnecting in
  if disconnecting == false {
    disconnecting = true
    proceed = true
  }
}
```
3. using the same variable name slightly modified:
```
self.disconnecting.modify { _disconnecting in
  if _disconnecting == false {
    _disconnecting = true
    proceed = true
  }
}
```
4. same as 2. or 3. plus adding the argument type explicitly:
```
self.disconnecting.modify { (disconnecting: inout Bool) in
  if disconnecting == false {
    disconnecting = true
    proceed = true
  }
}
```
</blockquote></details>

My rule on bike shed debates like this is - dev decides. And you are the dev.

---

*[ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift, line 30 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM4ZUl1QkSqLudI6Uw:-Kp_ruAwvVuraTvMOmOh:b32viz) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCoreTests/SocketConnectionTests/VirtualSocketTests.swift#L30)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

OK, I see, it's doable, but I don't think we should delay merging this PR to have some more tests, since we are passing 100% of ThaliTest and also ThaliTestApp works just fine. 
</blockquote></details>

:P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-:-Kp_rzrAx_keoswaEPJt:b-j48xkd)*

**Comment by enricogior** [comment]
I spoke to Jarek and we agreed that given I didn't change the already existing convention of using the $0 shortcut, we will open a new issue for it and fix it after the merge.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-:-Kpa3jU77JwbVLSzYg5d:b-6fw7l7)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/AdvertiserRelay.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpM3C3SzdJ6Im_KjOJG:-Kpa5ZE_9GH8KUPaS4PJ:bdelmol) ([raw file](https://github.com/thaliproject/thali-ios/blob/1a5c6fd17acfeef32b62f45fda1c11a8b65ea81d/ThaliCore/SocketConnection/AdvertiserRelay.swift#L45)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

My rule on bike shed debates like this is - dev decides. And you are the dev.
</blockquote></details>

I spoke to Jarek and we agreed that given I didn't change the already existing convention of using the $0 shortcut, we will open a new issue for it and fix it after the merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by lesn1kk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/MultipeerConnectivity/Advertiser.swift, line 114 at r2](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpnCkrRLbA7bvMqSln6:-KpnCkrRLbA7bvMqSln7:b-eqtr65) ([raw file](https://github.com/thaliproject/thali-ios/blob/aa4ac499e17c48b5fe3ea46f0522acf2871e0a6b/ThaliCore/MultipeerConnectivity/Advertiser.swift#L114)):*
> ```Swift
>   func startAdvertising(_ startAdvertisingErrorHandler: @escaping (Error) -> Void) {
>     if !advertising {
>       print("[ThaliCore] Advertiser.\(#function) with peerID:\(self.peer.uuid)")
> ```

I know I already asked about this, but what about extended logging in production code? Do we really need it ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
*[ThaliCore/MultipeerConnectivity/Advertiser.swift, line 114 at r2](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpnCkrRLbA7bvMqSln6:-KpnENnoWGFg2QYmhC4t:bk8psz6) ([raw file](https://github.com/thaliproject/thali-ios/blob/aa4ac499e17c48b5fe3ea46f0522acf2871e0a6b/ThaliCore/MultipeerConnectivity/Advertiser.swift#L114)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

I know I already asked about this, but what about extended logging in production code? Do we really need it ?
</blockquote></details>

For now I would prefer to leave all the logging as it is, but I will open an issue to tack it and reduce/disable logging for production.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by lesn1kk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/MultipeerConnectivity/Browser.swift, line 28 at r2](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpnFZ0mm6AFWbCJq_VP:-KpnFZ0mm6AFWbCJq_VQ:b-fv82il) ([raw file](https://github.com/thaliproject/thali-ios/blob/aa4ac499e17c48b5fe3ea46f0522acf2871e0a6b/ThaliCore/MultipeerConnectivity/Browser.swift#L28)):*
> ```Swift
>    Timeout for inviting a remote peer to a MCSession.
>    */
>   internal let invitePeerTimeout: TimeInterval = 2.5
> ```

To be honest I am little bit worried about setting this timeInterval to 2.5 based on trial and error. I know we are really heavily testing thali in our tests, however you never know how it will behave in real environment. For now I am ok with this, but I suggest to open an issue to track if this timeout actually does its job in real usage, for example, in TeamONE app.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by lesn1kk** [comment]
Please refer to my last comment and then :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-:-KpnGiJ0mBJZF6Hzu6Nb:bk86it)*

**Comment by enricogior** [comment]
*[ThaliCore/MultipeerConnectivity/Browser.swift, line 28 at r2](https://reviewable.io:443/reviews/thaliproject/thali-ios/10#-KpnFZ0mm6AFWbCJq_VP:-KpnL60NkxRdHZAtIPvr:b-896fix) ([raw file](https://github.com/thaliproject/thali-ios/blob/aa4ac499e17c48b5fe3ea46f0522acf2871e0a6b/ThaliCore/MultipeerConnectivity/Browser.swift#L28)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

To be honest I am little bit worried about setting this timeInterval to 2.5 based on trial and error. I know we are really heavily testing thali in our tests, however you never know how it will behave in real environment. For now I am ok with this, but I suggest to open an issue to track if this timeout actually does its job in real usage, for example, in TeamONE app.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/10)*

**Comment by enricogior** [comment]
Created the issues to track what emerged from the code review:
https://github.com/thaliproject/Thali_CordovaPlugin/issues/1949
https://github.com/thaliproject/Thali_CordovaPlugin/issues/1950
Giving there aren't other things to discuss, we'll proceed merging the PR.

**Pull request merged**
