### PR TITLE
Fix issue when iOS native can't handle parallel connections from node

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/5)

### CODE REVIEW

**Comment by asuhodolov** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/5#-:-Kh7_FasuRqYB7IJceB6:bnfp4nl)*

**Comment by asuhodolov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/5)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 80 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/5#-Kh8JAEs-gZjhgE6f2oQ:-Kh8JAEs-gZjhgE6f2oR:bxb9a90) ([raw file](https://github.com/thaliproject/thali-ios/blob/b7b5677567f14c0b50e7c7a7b5a8e0ec93023e54/ThaliCore/SocketConnection/TCPClient.swift#L80)):*
> ```Swift
> 
>   func socketDidCloseReadStream(_ sock: GCDAsyncSocket) {
>     sock.disconnect()
> ```

NB: We should have a comment to explain why we did this, e.g. disabled auto disconnect and handle it ourselves.. Linking to a bug that explains it is fine.

---

*[ThaliCore/SocketConnection/TCPListener.swift, line 106 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/5#-Kh8JDo6eYKNy0zoDP33:-Kh8JDo6eYKNy0zoDP34:b-dam82r) ([raw file](https://github.com/thaliproject/thali-ios/blob/b7b5677567f14c0b50e7c7a7b5a8e0ec93023e54/ThaliCore/SocketConnection/TCPListener.swift#L106)):*
> ```Swift
> 
>   func socketDidCloseReadStream(_ sock: GCDAsyncSocket) {
>     sock.disconnect()
> ```

NB: Same comment as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/5#-:-Kh8JGmSd9T4HkBaDpVl:bnfp4nl)*

**Comment by evabishchevich** [comment]
Already implemented in #6

**Pull request closed without merging**
