### PR TITLE
Fix tests which fail in native mode. 

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/6)

### CODE REVIEW

**Comment by asuhodolov** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-:-Khvp5tlq3tbA1yBp6Nn:bnfp4nl)*

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 70 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwYtwADZKAsCDV4rV4:-KhwYtwADZKAsCDV4rV5:b-7560tb) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L70)):*
> ```Swift
> 
>   func socket(_ sock: GCDAsyncSocket, didWriteDataWithTag tag: Int) {
>     sock.readData(withTimeout: -1, tag: 0)
> ```

This is Yaron's (@yaronyg) comment from [PR #3 ](https://reviewable.io/reviews/thaliproject/thali-ios/3#-Kh8IVrrPNSDZZrIDWkL):

It seems scary to leave a read open indefinitely. How do we make sure this can't be used as a way to drain someone's battery? What other timeouts do we have?

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 79 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwZS3gMop0bfASjQk-:-KhwZS3gMop0bfASjQk0:b6o75ct) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L79)):*
> ```Swift
> 
>   func socketDidCloseReadStream(_ sock: GCDAsyncSocket) {
>     sock.disconnect()
> ```

This is Yaron's (@yaronyg) comment from [PR #5](https://reviewable.io/reviews/thaliproject/thali-ios/5#-Kh8JAEs-gZjhgE6f2oQ):

NB: We should have a comment to explain why we did this, e.g. disabled auto disconnect and handle it ourselves.. Linking to a bug that explains it is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by yaronyg** [comment]
Please respond to the comments. Thanks!

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 70 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwYtwADZKAsCDV4rV4:-KhxFUtAyXz9aewZUV_z:b-5am3ob) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L70)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

This is Yaron's (@yaronyg) comment from [PR #3 ](https://reviewable.io/reviews/thaliproject/thali-ios/3#-Kh8IVrrPNSDZZrIDWkL):

It seems scary to leave a read open indefinitely. How do we make sure this can't be used as a way to drain someone's battery? What other timeouts do we have?
</blockquote></details>

Any response?

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 79 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwZS3gMop0bfASjQk-:-KhxFYSt_aieU0dsgW4g:b-5am3ob) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L79)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

This is Yaron's (@yaronyg) comment from [PR #5](https://reviewable.io/reviews/thaliproject/thali-ios/5#-Kh8JAEs-gZjhgE6f2oQ):

NB: We should have a comment to explain why we did this, e.g. disabled auto disconnect and handle it ourselves.. Linking to a bug that explains it is fine.
</blockquote></details>

Any response?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-:-KhxFl1oK91hmVD3lTYq:b-8p4hl2)*

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 70 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwYtwADZKAsCDV4rV4:-Ki0k8jgPLRRtOQzeq_5:bebjngo) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L70)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Any response?
</blockquote></details>

Yes, for now we're using an infinite timeout.
First of all our specs doesn't say anything about how long the iOS native layer should wait for read/write events in socket.
We can use another positive timeout (30 or 90 sec as example), but we need to prove that it will be enough from perspective of TCP link. Because it is important to choose a timeout that is reasonable. Can we potentially receive a valid data with some delay (more than 90 seconds)?

IMHO initially by our design the iOS native layer should do basically 2 things: transfer data (explicitly) and track information about the state of TCP connection (implicitly) because we don't transmit the TCP data packet headers and the TCP control commands. Only the node layer see connection from TCP perspective. So if the answer on my first question is no, then only node layer should introduce such timeouts and handle it. As far as I remember we have them in node code. @opetkevich, could you please prove it?

So in the worst-case scenario node server for some reason can be freezed and in this case native layer potentially will be waiting for TCP read events. But on the other hand if node server is freezed we can't assume that application will work at all. In short I don't think that we add more defense here than we have.

Also I've done quick search on github to check how similar functional is implemented in open-source libraries with communication via sockets. Looks like many of them use infinite timeout in such cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 70 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwYtwADZKAsCDV4rV4:-Ki22OhTtESyYZY1nQG9:b-vhwxc6) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L70)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

Yes, for now we're using an infinite timeout.
First of all our specs doesn't say anything about how long the iOS native layer should wait for read/write events in socket.
We can use another positive timeout (30 or 90 sec as example), but we need to prove that it will be enough from perspective of TCP link. Because it is important to choose a timeout that is reasonable. Can we potentially receive a valid data with some delay (more than 90 seconds)?

IMHO initially by our design the iOS native layer should do basically 2 things: transfer data (explicitly) and track information about the state of TCP connection (implicitly) because we don't transmit the TCP data packet headers and the TCP control commands. Only the node layer see connection from TCP perspective. So if the answer on my first question is no, then only node layer should introduce such timeouts and handle it. As far as I remember we have them in node code. @opetkevich, could you please prove it?

So in the worst-case scenario node server for some reason can be freezed and in this case native layer potentially will be waiting for TCP read events. But on the other hand if node server is freezed we can't assume that application will work at all. In short I don't think that we add more defense here than we have.

Also I've done quick search on github to check how similar functional is implemented in open-source libraries with communication via sockets. Looks like many of them use infinite timeout in such cases.
</blockquote></details>

Sounds reasonable. We'll drive from the node layer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 79 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwZS3gMop0bfASjQk-:-Ki6gDy4mPLMPxVmTis7:bkavg98) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L79)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Any response?
</blockquote></details>

@dersim-davaod Please, add a comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by evabishchevich** [comment]
Sounds reasonable. We'll drive from the node layer. 
@yaronyg Does it mean that we have LGTM from you?

**Comment by yaronyg** [comment]
Still waiting for a response from Dersim on a question I had.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-:-Ki7KAU7Sc1uozNA21ZW:b-o1jwsv)*

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 79 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwZS3gMop0bfASjQk-:-KiDz1RyQAGXBira3B6X:bfwf7o4) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L79)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

@dersim-davaod Please, add a comment
</blockquote></details>

@yaronyg, sorry for the delay
I've investigated issue with replication in ThaliTestApp and the TCP stack in native layer. We fixed tests from ticket #9 and then @opetkevich has add some tests that were failing (tests with HTTP request-responces between peers).

For now actually looks like we don't need this code at all. I mean `autoDisconnectOnClosedReadStream = true` does exactly what we're doing here. I will update this PR and will remove `sock.diconnect()` lines.

Instead of that, we need to have`autoDisconnectOnClosedReadStream = true`, but we don't need to disconnect socket in `socketDidCloseReadStream` method. The node remote endpoint can close its write stream. Our native TCP socket would then be notified that there is no more data to be read, but our native TCP socket would still be writeable and the remote endpoint in native layer could continue to receive our data. This is actually why we had some issues. For example socket.end() method which we're using (from node's net) do following: it sends FIN packet and then native TCP socket can disconnect link (by sending FIN+ACK), but we still need alive socket, so `autoDisconnectOnClosedReadStream` should be true for us if we want to transfer data via this TCP link. In some terms my answer is similar to answer above: node layer starts request, thus node layer should close connection, because only node layer knows when it should be closed.

Please see more explanation [here](https://github.com/robbiehanson/CocoaAsyncSocket/wiki/Reference_GCDAsyncSocket#autoDisconnectOnClosedReadStream).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ThaliCore/SocketConnection/TCPClient.swift, line 79 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/6#-KhwZS3gMop0bfASjQk-:-KiGWX6wHB5vJGt8xrT4:b148jko) ([raw file](https://github.com/thaliproject/thali-ios/blob/1460248937751967665cbc5a89a1481b0339da0b/ThaliCore/SocketConnection/TCPClient.swift#L79)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

@yaronyg, sorry for the delay
I've investigated issue with replication in ThaliTestApp and the TCP stack in native layer. We fixed tests from ticket #9 and then @opetkevich has add some tests that were failing (tests with HTTP request-responces between peers).

For now actually looks like we don't need this code at all. I mean `autoDisconnectOnClosedReadStream = true` does exactly what we're doing here. I will update this PR and will remove `sock.diconnect()` lines.

Instead of that, we need to have`autoDisconnectOnClosedReadStream = true`, but we don't need to disconnect socket in `socketDidCloseReadStream` method. The node remote endpoint can close its write stream. Our native TCP socket would then be notified that there is no more data to be read, but our native TCP socket would still be writeable and the remote endpoint in native layer could continue to receive our data. This is actually why we had some issues. For example socket.end() method which we're using (from node's net) do following: it sends FIN packet and then native TCP socket can disconnect link (by sending FIN+ACK), but we still need alive socket, so `autoDisconnectOnClosedReadStream` should be true for us if we want to transfer data via this TCP link. In some terms my answer is similar to answer above: node layer starts request, thus node layer should close connection, because only node layer knows when it should be closed.

Please see more explanation [here](https://github.com/robbiehanson/CocoaAsyncSocket/wiki/Reference_GCDAsyncSocket#autoDisconnectOnClosedReadStream).
</blockquote></details>

OKee Dokee. Looking forward to those changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/6)*

**Comment by dersim-davaod** [comment]
I don't know why but I can't reopen this PR, because of "There are no new commits on the master_dersim_ticket9 branch.".
Looks like github has lost `HEAD` of `master_dersim_ticket9` branch (?)
In the worst case I'll create a new PR today (from `master_dersim_ticket9` into `master`).

**Pull request closed without merging**
