### PR TITLE
Fix tests which fail in native mode.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This is basically the same PR as PR thaliproject/thali-ios#6 with improvements for http tests in node.js.

It should be tested and merged with [#1855](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1855) and [#1858](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1858) PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/7)

### CODE REVIEW

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/7#-:-KiW6rOagBLLJG2Raqoo:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/7#-:-KiZH0nYm3zhxuGXmf-f:bnfp4nl)*

**Comment by jareksl** [comment]
Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/7)*

**Comment by asuhodolov** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/7#-:-KidiSYPlKXPTi1UV8Cv:bnfp4nl)*

**Pull request merged**
