### PR TITLE
Data queue async processing

### PR DESCRIPTION
**Pull request by enricogior**
Fixes Thali issues:
https://github.com/thaliproject/Thali_CordovaPlugin/issues/1963
https://github.com/thaliproject/Thali_CordovaPlugin/issues/1966

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/12)

### CODE REVIEW

**Comment by yaronyg** [comment]
Please see inline coments

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/SocketConnection/VirtualSocket.swift, line 183 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-Kwa7mveYGreWQ0TS8bF:-Kwa7mveYGreWQ0TS8bG:b4rqoab) ([raw file](https://github.com/thaliproject/thali-ios/blob/802a2b0b8b4c2058a5ef945d9519c041de69e8c8/ThaliCore/SocketConnection/VirtualSocket.swift#L183)):*
> ```Swift
> 
>     while dataQueue.count > 0 {
>       dataQueueMutex.lock()
> ```

All this manual locking and unlocking is guaranteed to introduce bugs. Aren't there multi-thread safe classes somewhere?

---

*[ThaliCore/SocketConnection/VirtualSocket.swift, line 199 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-Kwa89xOA6QzQtyemukr:-Kwa89xOA6QzQtyemuks:b-5bk590) ([raw file](https://github.com/thaliproject/thali-ios/blob/802a2b0b8b4c2058a5ef945d9519c041de69e8c8/ThaliCore/SocketConnection/VirtualSocket.swift#L199)):*
> ```Swift
>         }
> 
>         if bytesWritten == chunkLength {
> ```

Swift has support for switch statements, why isn't that used instead of the cascading if statements?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-:-Kwa8L2Nw23LE--vHfa8:b-3nxigw)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/VirtualSocket.swift, line 199 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-Kwa89xOA6QzQtyemukr:-Kwd08SiMjaGya09Ge8W:bmf0fbg) ([raw file](https://github.com/thaliproject/thali-ios/blob/802a2b0b8b4c2058a5ef945d9519c041de69e8c8/ThaliCore/SocketConnection/VirtualSocket.swift#L199)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Swift has support for switch statements, why isn't that used instead of the cascading if statements?
</blockquote></details>

Originally there were only two cases, then I added a third one and didn't bother changing to a 'switch' statement. I would change it as you requested but that would require to do the full testing both on my side and on Rockwell side and that is not an option at least not for me since we don't have the budget. I'm still planning to do one more PR for issue 1965 but that will require its own testing. I leave it to you and Rockwell to decide what the priorities are, I can only work on this or on the crashing issue 1965, clearly for me the choice is already set on 1965.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/12)*

**Comment by enricogior** [comment]
Thanks, I replied.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-:-Kwd2jE8rS6Fm_YHGg69:b-5qmqz6)*

**Comment by enricogior** [comment]
*[ThaliCore/SocketConnection/VirtualSocket.swift, line 183 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-Kwa7mveYGreWQ0TS8bF:-KwczSLwKlIfiFIWodh6:b-l8fibp) ([raw file](https://github.com/thaliproject/thali-ios/blob/802a2b0b8b4c2058a5ef945d9519c041de69e8c8/ThaliCore/SocketConnection/VirtualSocket.swift#L183)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

All this manual locking and unlocking is guaranteed to introduce bugs. Aren't there multi-thread safe classes somewhere?
</blockquote></details>

Swift is quite immature, there isn't a native support for thread-safe queues.
In this case the locking is pretty much straight forward and safe: one function that add items, one function that removes items that does nothing else beside removing items while holding the lock.
I don't see how this can be causing dead lock.
The real problem with locking in ThaliCore is in the extensive use of the Atomic class that is far from ideal and in fact it was misused and causing dead locks in the code. I fixed those dead locks but didn't have the budget for a complete re-write. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/12)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[ThaliCore/SocketConnection/VirtualSocket.swift, line 199 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-Kwa89xOA6QzQtyemukr:-Kwg2iIGpuRC0qTVmJXZ:b-1jn3at) ([raw file](https://github.com/thaliproject/thali-ios/blob/802a2b0b8b4c2058a5ef945d9519c041de69e8c8/ThaliCore/SocketConnection/VirtualSocket.swift#L199)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Originally there were only two cases, then I added a third one and didn't bother changing to a 'switch' statement. I would change it as you requested but that would require to do the full testing both on my side and on Rockwell side and that is not an option at least not for me since we don't have the budget. I'm still planning to do one more PR for issue 1965 but that will require its own testing. I leave it to you and Rockwell to decide what the priorities are, I can only work on this or on the crashing issue 1965, clearly for me the choice is already set on 1965.
</blockquote></details>

Sigh.... got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/12#-:-Kwg2lPMfWj_FemiXS6A:bnfp4nl)*

**Pull request merged**
