### PR TITLE
Add errorDescription to ThaliCoreError #1843

### PR DESCRIPTION
**Pull request by asuhodolov**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali-ios/1)

### CODE REVIEW

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[ThaliCore/Core/ThaliCoreError.swift, line 23 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/1#-KgF6nskIruPLsAxAgB9:-KgF6nskIruPLsAxAgBA:b-u1u2ze) ([raw file](https://github.com/thaliproject/thali-ios/blob/beb89cf1b0226a0081a383170f69b50af39c118f/ThaliCore/Core/ThaliCoreError.swift#L23)):*
> ```Swift
>   
>   public static var errorDomain: String {
>     return "ThaliCoreError"
> ```

NB:
`"org.thaliproject.ThaliCoreError"` sounds for me like more reliable errorDomain

---

*[ThaliCore/Core/ThaliCoreError.swift, line 51 at r1](https://reviewable.io:443/reviews/thaliproject/thali-ios/1#-KgF8Mht0E-PS035-12i:-KgF8Mht0E-PS035-12j:b-1cdqr6) ([raw file](https://github.com/thaliproject/thali-ios/blob/beb89cf1b0226a0081a383170f69b50af39c118f/ThaliCore/Core/ThaliCoreError.swift#L51)):*
> ```Swift
>   /// The user-info dictionary.
>   public var errorUserInfo: [String : Any] {
>     return ["ErrorDescription": description]
> ```

NB:
Maybe it's better to use `NSLocalizedDescriptionKey`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/1)*

**Comment by baydet** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/1)*

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/1)*

**Comment by asuhodolov** [comment]
Updated errorDescription key to NSLocalizedDescriptionKey.
Error domain changed to "org.thaliproject.ThaliCoreError"

**Comment by asuhodolov** [comment]
@yaronyg could we merge?

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/1#-:-KgKQkXw4ubOabY0NRM9:bnfp4nl)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali-ios/1#-:-KgUNT6NEsVM7IIkU4eV:bnfp4nl)*

**Pull request merged**
